routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('comingsoon');
});*/

Route::get('/', function () {
    return view('pages.home');
});

Route::get('/error', function () {
    return view('error');
});

/*Route::get('/chat', function () {
    return view('customerdashboard.chat');
});*/

Auth::routes();

Route::get('/chat', 'ChatController@index');
Route::post('ajaxRequest', 'ChatController@saveChat');
Route::get('getChat/{hireid}/{jobid}','ChatController@getChat');
Route::get('/chathistory/{jobid}','ChatController@getChathistory');
Route::get('/support', 'ChatController@show_adminchat');
Route::post('adminajaxRequest', 'ChatController@saveadminChat');
Route::get('getadminChat/{senderid}/{receiverid}','ChatController@getadminChat');
Route::get('getadminChatmsgcnt/{sndid}/{rcvid}','ChatController@getadminChatmsgcnt');

Route::get('/workeradminchat','ChatController@workeradminchat');
Route::post('workeradminajaxRequest', 'ChatController@saveworkeradminChat');
Route::get('getworkeradminChat/{senderid}/{receiverid}','ChatController@getworkeradminChat');

Route::get('/customeradminchat','ChatController@customeradminchat');
Route::post('customeradminajaxRequest', 'ChatController@savecustomeradminChat');
Route::get('getcustomeradminChat/{senderid}/{receiverid}','ChatController@getcustomeradminChat');

Route::get('/redirect/{service}', 'SocialAuthGoogleController@redirect');
Route::get('/callback/{service}', 'SocialAuthGoogleController@callback');

Route::get('/facebookredirect/{service}', 'SocialAuthFacebookController@facebookredirect');
Route::get('/facebookcallback/{service}', 'SocialAuthFacebookController@facebookcallback');


Route::get('/home', 'HomeController@index')->name('home');
Route::post('/home/store', 'HomeController@store');

Route::get('/pricing', 'PricingController@index')->name('pricing');
Route::get('/aboutus', 'AboutusController@index')->name('aboutus');

Route::get('auth/facebook', 'Auth/LoginController@redirectToProvider');
Route::get('auth/facebook/callback', 'Auth/LoginController@handleProviderCallback');
Route::get('userregister', 'Auth\LoginController@userregister');
Route::POST('/store','UsersController@store');
Route::GET('/storeclient','UsersController@storeclient');
Route::get('/checkuseremail', 'UsersController@checkuseremail');
Route::get('/checkloginemail', 'UsersController@checkloginemail');
/*Route::get('/checkloginpassword', 'UsersController@checkloginpassword');*/

Route::resource('jobpost','JobpostController');
Route::GET('/getequipment','JobpostController@getequipment');
Route::GET('/jobstore','JobpostController@jobstore');
Route::GET('/updatejob','JobpostController@updatejob');
Route::GET('/getalldata','JobpostController@getalldata');
Route::get('/reciept', 'JobpostController@reciept');
Route::get('/checkrefferalcode', 'JobpostController@checkrefferalcode');
Route::GET('/notitysec', 'JobpostController@notitysec');
Route::GET('/workernotitysec', 'JobpostController@workernotitysec');
Route::GET('/completeupdate', 'WorkerjobsController@complete_btn_status_update');
Route::GET('/cancelledupdate', 'WorkerjobsController@cancelled_btn_status_update');
Route::GET('/customercompleteupdate', 'CustomernotificationController@complete_btn_status_update');
Route::GET('/customercancelledupdate', 'CustomernotificationController@cancelled_btn_status_update');
Route::POST('/customerfeedback', 'CustomernotificationController@customer_feedback');
Route::POST('/workerfeedback', 'WorkerjobsController@worker_feedback');

Route::resource('workerdashboard','WorkerdashboardController');
Route::POST('/workerdashboard/store','WorkerdashboardController@store');
Route::get('/jobpreference','WorkerdashboardController@jobpreference');
Route::GET('/workerexperience','WorkerdashboardController@workerexperience');
Route::GET('/updtworkexp','WorkerdashboardController@updtworkexp');
Route::GET('/workerequipment','WorkerdashboardController@workerequipment');
Route::GET('/updtworkequ','WorkerdashboardController@updtworkequ');

Route::resource('customerdashboard','CustomerdashboardController');

Route::resource('customerpay', 'CustomerpaymentController');
Route::resource('customershare', 'CustomershareController');
Route::resource('customerjobs', 'CustomerjobsController');
Route::resource('customerjobhistory', 'CustomerjobhistoryController');
Route::resource('customergift', 'CustomergiftController');
Route::resource('customerhelp', 'CustomerhelpController');

Route::resource('workerpayment', 'WorkerpaymentController');
Route::resource('workerjobs', 'WorkerjobsController');
//================ 12-02-2019 ================//
Route::GET('/updateworkedhour', 'WorkerjobsController@updateWorkedHour'); 
Route::GET('/hourdetails', 'CustomernotificationController@hourDetails'); 
Route::GET('/updatehourstatus', 'CustomernotificationController@updateHourStatus'); 
Route::GET('/pendingpayments', 'AdminclientpaymentController@pendingPayments'); 
Route::GET('/adminallpayments', 'AdminclientpaymentController@adminAllPayments'); 
Route::GET('/createuserstripe', 'JobpostController@createUserStripe'); 
Route::GET('/processclientpayments', 'AdminclientpaymentController@processClientPayments'); 
Route::GET('/updatepoststatus', 'JobpostController@updatePostStatus'); 
Route::GET('/readallnotifications', 'JobpostController@readAllNotifications'); 
Route::GET('/updateworkerpayment', 'AdminrequestpaymentController@updateWorkerPayment'); 
//============================================//
Route::resource('workerprofile','WorkerdashboardController');
Route::resource('socialworkerprofile','WorkerdashboardController');
Route::resource('workershare','WorkershareController');
Route::resource('workerpay','WorkerpayController');
Route::resource('workerhelp','WorkerhelpController');
Route::GET('adminworker/update','AdminworkerController@update');
Route::GET('admincustomer/update','AdmincustomerController@update');

Route::GET('admindashboard','AdmindashboardController@index');

Route::POST('/adminupdate/worker','AdminupdateController@worker');
Route::POST('/adminupdate/customer','AdminupdateController@customer');
Route::resource('adminjobs','AdminjobsController');
Route::resource('adminhire','AdminhireController');
Route::POST('adminhirecreate','AdminhireController@adminhirecreate');
Route::GET('viewall','AdminhireController@viewall');
Route::resource('adminmessages','AdminmessagesController');
Route::POST('adminmessages/send_mail','AdminmessagesController@send_mail');
Route::resource('clientpayment','AdminclientpaymentController');
Route::resource('requestpayment','AdminrequestpaymentController');
Route::resource('adminprofile','AdminprofileController');
Route::resource('adminnotification','AdminnotificationController');
Route::resource('admincustomer','AdmincustomerController');
Route::resource('adminworker','AdminworkerController');
Route::resource('adminbussiness','AdminbussinessController');
Route::POST('/workerpay/store','WorkerpayController@store');
Route::POST('/update','WorkerpayController@update');
Route::POST('/update', 'WorkerjobsController@update');
Route::resource('customernotification', 'CustomernotificationController');
Route::POST('/update', 'CustomernotificationController@update');
Route::resource('workernotification', 'WorkernotificationController');
Route::POST('/update', 'WorkernotificationController@update');
Route::POST('/update', 'CustomerjobhistoryController@update');
Route::GET('/updatestatus', 'CustomerdashboardController@update_status');
Route::GET('/workersendinvitation', 'WorkershareController@worker_send_invitation_code');
Route::GET('/customersendinvitation', 'CustomershareController@customer_send_invitation_code');
Route::resource('customerpayment', 'CustomerpaymentsController');
Route::GET('/rejectpayment', 'AdminrequestpaymentController@reject_payment_update');

Route::GET('/forgetpassword', 'Auth\ForgotPasswordController@sendemail');
Route::GET('/checkforgetemail', 'Auth\ForgotPasswordController@checkforgotemail');

Route::POST('/workerprofileupdate/{id}','WorkerdashboardController@worker_profile_update');

resources/views/admin/clientpayment/allpayments.blade.php
@extends('layouts.defautladmin')

@section('title', 'Adminpayments')

@section('content')

<div class="content customers_detail">
  <div class="col-sm-12">
      <div class="adminjob">
    <h2>All Payments<span class="badge pull-right"> 
  <!--  <form action="" method="get"><input type="text" placeholder="Search.." name="search">
        </form> </h2> -->
        </div>
  </div>


  <div class="col-sm-12">
    <?php 
  //echo'<pre>';
  //print_r($allpayments);
  //echo'</pre>';

  ?>
      <table class="table-width col_or">
        <thead>
          <tr class="table-active">
            <th class="col3">Worker Name</th>
            <th class="col2">Job Name</th>
            <th class="col2">Job Status</th>
            <th class="col2">Routing Number</th>
            <th class="col2">Account Number</th>
            <th class="col2">Client Amount</th>
            <th class="col3">Client Payment Status</th>
            <th class="col2">Worker Amount</th>
            <th class="col3">Worker Payment Status</th>
            
          </tr>
        </thead>
      <tbody>
          <?php if( count($allpayments) > 0 ):
          foreach ($allpayments as $paymentDetails) {
            $worker_name = $paymentDetails->name;
            $worker_id = $paymentDetails->worker_id;
            $client_id = $paymentDetails->client_id;
            $client_job_id = $paymentDetails->client_job_id;
            $work_payment_data = DB::table('workerpayment')->where('user_id', $worker_id)->first();
            ?>
          <tr>  
            <td><?php echo $worker_name; ?></td>
            <td><?php echo $paymentDetails->cat_name; ?></td>
            <td><?php echo $paymentDetails->job_status; ?></td>
            <td><?php if( !empty($work_payment_data) ): echo $work_payment_data->bank_routing_number; endif; ?></td>
            <td><?php if( !empty($work_payment_data) ): echo $work_payment_data->bank_account_number; endif; ?></td>
            <td>$<?php echo $paymentDetails->amount_paid;?></td>
            <td><label class="badge badge-success">Success</label></td>
            <td>$<?php echo $paymentDetails->amount_paid;?></td>
            <td><?php if( $paymentDetails->worker_payment_status == 1 ): echo '<label class="badge badge-success">Success</label>'; else : echo  '<label class="badge badge-danger">Rejected</label>'; endif; ?></td>
            <td>
              
            </td>
          </tr>
            <?php
          }
          else:
            echo'<tr><td colspan="6">No Record found</td></tr>';
          endif;  
          ?>    
        </tbody>
      </table>
            <div class="content pagi_div">    

    
</div>
</div>
  
@include('layouts.footer_admin') 
  
</div> 
<style type="text/css">
input[type="text"] {
    width: 79%;
}
.submit_btn {
  background: #25a6dc;
  color: #fff;
  font-weight: bold;
  border: none;
  padding: 6px 28px 7px 28px;
  border-radius: 5px;
}
.modal-title {
  text-align: center;
  font-size: 24px;
  font-weight: bold;
}
.markmodel {
    background: #25a6dc;
    border: none;
    padding: 7px 2px;
    border-radius: 5px;
    width: 100%;
    margin-bottom: 2px;
    font-size: 12px;
}
#reject_btn {
    background: #ff0000;
border: none;
padding: 7px 2px;
border-radius: 5px;
width: 100%;
margin-bottom: 2px;
font-size: 12px;
}
</style>
@stop

resources/views/admin/clientpayment/edit.blade.php
@extends('layouts.defautladmin')

@section('title','Update User')

@section('content')
<div class="content Contextua_sec customers_detail">
    <h1>Edit Customer Profile</h1>
    @include('layouts.flash-message') 
<form method="POST" action="{{url('/')}}/adminupdate/customer" id="updateprofile" accept-charset="UTF-8" enctype='multipart/form-data'>
  {{ csrf_field() }}
  <div class="row bussiness">
<div class="col-sm-6"><label>First Name</label><input type="text" name="firstname" value="{{ $customer_info->firstname }}" required="required"></div>
<div class="col-sm-6"><label>Last Name</label><input type="text" name="lastname" value="{{ $customer_info->lastname }}" required="required"></div></div>
<div class="row bussiness">
<div class="col-sm-6"><label>Email Address</label><input type="text" name="email" value="{{ $customer_info->email }}" required="required"></div>
<div class="col-sm-6"><label>Phone</label><input type="text" name="phone" value="{{ $customer_info->phone }}" required="required"  onkeypress="this.value=this.value.replace(/[^0-9]/g,'');"></div>
</div>
<div class="row bussiness">
<div class="col-sm-6"><label>Password</label><input type="password" name="password" id="password"></div>    
<div class="col-sm-6"><label>Confirm Password</label><input type="password" name="confpwd" id="password"></div>
</div>
<div class="row bussiness">
  <div class="col-sm-6">
  <label>Profile Image</label>
  <input type="file" name="input_img">
<?php
if($customer_info->image==''){
  ?>
<img class="profileimage" src="{{ url('/public/admin/images/admin.jpg') }}">
<?php
}
else{
  ?>
<img class="profileimage" src="{{ url('/public/uploads/profile/')}}/{{ $customer_info->image }}">
<?php
}
?>
</div></div>
<div class="row bussiness">
<div class="col-sm-6"><label>City</label><input type="text" name="city" value="{{ $customer_info->city }}"></div>
<div class="col-sm-6"><label>State</label><input type="text" name="state" value="{{ $customer_info->state }}"></div></div>
<div class="row bussiness">
    <div class="col-sm-6"><label>Address</label><textarea name="address">{{ $customer_info->address }}</textarea>
</div>
	<div class="col-sm-6"><label>Address1</label><textarea name="address1">{{ $customer_info->address1 }}</textarea>
</div></div>
<div class="row bussiness"><div class="col-sm-6">
<input type="hidden" name="id" value="{{ $customer_info->id }}">
	<input type="submit" name="submit" value="Update" class="update_buss"></div></div>
</form>
<script type="text/javascript">
 $(document).ready( function() {
 $.validator.addMethod("alphaLetterNumber", function(value, element) {
     return this.optional(element) || value == value.match(/^[a-zA-Z0-9]+$/) && value.match(/[a-zA-Z0-9]/);
    });

  $.validator.addMethod("alphaLetterNumberSpace", function(value, element) {
     return this.optional(element) || value == value.match(/^[ a-zA-Z0-9]+$/) && value.match(/[a-zA-Z0-9]/);
    });

  $.validator.addMethod("alphaLetter", function(value, element) {
     return this.optional(element) || value == value.match(/^[ a-zA-Z]+$/) && value.match(/[a-zA-Z]/);
    });
     $.validator.addMethod("valueNotEquals", function(value, element, arg){
     return arg !== value;
  }, "Value must not equal arg.");
 $( "#updateprofile" ).validate({
  rules: {
                firstname: {
                    required: true,
                    alphaLetter:true,
                    minlength: 2,
                    maxlength: 150
                },
                lastname: {
                    required: true,
                    alphaLetter: true,
                    minlength: 2,
                    maxlength: 60
                },
                email: {
                    required: true,
                    email: true
                },
                phone: {
                  required: true,
                  minlength: 10,
                  maxlength: 14
                },
                address: {
                    required: true,
                    minlength: 6,
                    maxlength: 60
                },
                address1: {
                    required: true,
                    minlength: 6,
                    maxlength: 60
                },
                city: {
                    required: true
                },
                state: {
                    required: true
                }
  },
  messages: {
              firstname: {
                  required: "Please enter your firstname.",
                   alphaLetter:"Only letters are allowed",
                  minlength: "Minimum 2 characters required.",
                  maxlength: "Maximum 150 characters allowed."
                },
              lastname: {
                  required: "Please enter your lastname.",
                  alphaLetter:"Only letters are allowed",
                  minlength: "Minimum 2 characters required.",
                  maxlength: "Maximum 60 characters allowed."
                },
             
              email: {
                  required: "Please enter your email.",
                  email: "Enter valid email."                 
                },
                phone: {
                  required: "Please enter your phone number.",
                  minlength: "Minimum 10 digits required.",
                  maxlength: "Maximum 14 digits required."
                },
                address: {
                  required: "Please enter your Address.",
                  minlength: "Minimum 6 characters required.",
                  maxlength: "Maximum 60 characters allowed."
                },
                address1: {
                  required: "Please enter your Address.",
                  minlength: "Minimum 6 characters required.",
                  maxlength: "Maximum 60 characters allowed."
                },
                city: {
                    required: "Please enter your City."
                },
                state: {
                    required: "Please enter your State."
                }
              },
             
         });  

 });
</script>
</div>
 </div>
<style type="text/css">
.bussiness label { width: 32% }	
.bussiness { margin: 10px 0 10px 0; }
textarea {
    border: 1px solid #25a6dc;
    border-radius: 5px;
    padding: 0px 10px;
    background-color: #e5f1f6;
}
#password {
    border: 1px solid #25a6dc;
    border-radius: 5px;
    padding: 0px 10px;
    background-color: #e5f1f6;
    height: 38px;
}
.update_buss {
    border: 1px solid #25a6dc;
    border-radius: 5px;
    padding: 0px 10px;
    background-color: #e5f1f6;	
    cursor: pointer;
    height: 36px;
}
</style> 
 @stop

resources/views/admin/clientpayment/index.blade.php
@extends('layouts.defautladmin')

@section('title', 'Admincustomer')

@section('content')


<div class="content customers_detail">
	<div class="col-sm-12">
	    <div class="adminjob">
		<h2>Clients Payment <span class="badge pull-right"> 
	<!-- <form action="" method="get"><input type="text" placeholder="Search.." name="search">
        <button type="submit"><i class="fa fa-search"></i></button></form> --></h2>
        </div>
	</div>
	<div class="col-sm-12">
		  <table class="table-width col_or">
		    <thead>
		      <tr class="table-active">
		        <th class="col4">Client Name</th>
		      	<th class="col5">Worker Name</th>
		        <th class="col5">Job Tittle</th>
		        <th class="col4">Amount</th>
		        <th class="col2">Action</th>
		      </tr>
		    </thead>
		    <?php
		    $count = 0;
		    ?>
		    @if($client_payment_info!='')
		    @foreach($client_payment_info as $client_payment)
		      <?php
		    	$client_jobid = $client_payment->client_jobid;
		    	$client_user_id = $client_payment->user_id;
		    	$hire_info = DB::table('hire')
		    		 ->where('client_job_id',$client_jobid)
                     ->first();
                ?>
                <?php
                if($hire_info!=''){
					$worker_id = $hire_info->worker_id;
				} else {
					$worker_id = '...';
				}
                $work_user = DB::table('users')->where('id', $worker_id)->first();
                if($work_user!=''){
					$workername = $work_user->firstname.' '.$work_user->lastname;
				} else {
					$workername = '...';
				}
                     
                $job_heading_id = $client_payment->job_heading;
				$job_heading_info = DB::table('categories')->where('id', $job_heading_id)->first();
				if($job_heading_info!=''){
					$job_heading = $job_heading_info->cat_name;
				} else {
					$job_heading = '...';
				}
                $client_user = DB::table('users')->where('id', $client_user_id)->first();
                if($client_user!=''){
					$client_name = $client_user->firstname.' '.$client_user->lastname;
				} else {
					$client_name = '...';
				}
                
                ?>
                
		        <tr>
		        <td class="col4">{{ $client_name }}</td>
		        <td style="color: #808080;" class="col5">{{ $workername }}</td>
		        <td class="col5">{{ $job_heading }}</td>
		        <td class="col4">{{ '$'.$client_payment->paid_amount }}</td>
		        <td class="col2"><a href="{{route('clientpayment.show',$client_payment->id)}}"><i class="fa fa-eye mr-3" aria-hidden="true"></i></a></td>
		      </tr>
@endforeach
@else
<tr>
	No Payment Here...
</tr>
@endif
		    </tbody>
		  </table>
	</div>
		
@include('layouts.footer_admin') 
  
</div> 
</div>
@stop

resources/views/admin/clientpayment/pendingpayments.blade.php
@extends('layouts.defautladmin')

@section('title', 'Admincustomer')

@section('content')

<?php
//echo'<pre>';
//print_r($pending_paymentData);        
//echo'</pre>';
?>

<div class="content customers_detail">
    <div class="col-sm-12">
        <div class="adminjob">
        <h2>Clients Payment <span class="badge pull-right"> 
    <!-- <form action="" method="get"><input type="text" placeholder="Search.." name="search">
        <button type="submit"><i class="fa fa-search"></i></button></form> --></h2>
        </div>
    </div>
    <div class="col-sm-12">
          <table class="table-width col_or">
            <thead>
              <tr class="table-active">
                <th class="col4">Client Name</th>
                <th class="col5">Worker Name</th>
                <th class="col5">Job Tittle</th>
                <th class="col4">Approved Time</th>
                <th class="col4">Amount</th>
                <th class="col2">Action</th>
              </tr>
            </thead>
            <?php 
            //echo'<pre>';
            //print_r($pending_paymentData );
            //echo'</pre>';
            if( !empty($pending_paymentData) ): 
                foreach ($pending_paymentData as $paymentData) {
                    # code...
                    $hireid = $paymentData->hireid;
                    $client_id = $paymentData->user_id;
                    $client_job_id = $paymentData->client_job_id;
                    $worker_id = $paymentData->worker_id;
                    $hours_to_complete = $paymentData->hours_to_complete;
                    $mints_to_complete = $paymentData->mints_to_complete;
                    $updated_hours = $paymentData->updated_hours;
                    $updated_mints = $paymentData->updated_mints;
                    $price_per_hour = 35;
                    $price_per_mint = 35 / 60;
                    if($updated_hours !='' && $updated_mints !=''){
                        $total_time_mints = intval($updated_hours) * 60 + intval($updated_mints);
                        $approved_time_formated = $updated_hours .' : '. $updated_mints .'hr';
                    }else{
                        $total_time_mints = intval($hours_to_complete) * 60 + intval($mints_to_complete); 
                        $approved_time_formated = $hours_to_complete .' : '. $mints_to_complete .'hr';
                    }

                    $clientDetails = DB::table('users')
                                    ->where('id', '=', $client_id )
                                    ->first();
               
            ?>
                <tr>
                <td class="col4"><?php echo $clientDetails->name; ?></td>
                <td style="" class="col5"><?php echo $paymentData->name; ?></td>
                <td class="col5"><?php echo $paymentData->cat_name; ?></td>
                <td class="col4"><label class="badge badge-success"><?php echo $approved_time_formated; ?></label></td>
                <td class="col4"><?php $total_amount = $total_time_mints *  $price_per_mint;  
                                //setlocale(LC_MONETARY,"en_US");
                                echo $amountToPay = money_format("$%i", round($total_amount));  
                                ?>
                </td>
                <td class="col2"><a href="#" class="payNow btn btn-primary" data-payableamount="<?php echo  $total_amount; ?>" data-clientid="<?php echo $client_id; ?>" data-jobid="<?php echo $client_job_id; ?>" data-workerid="<?php echo $worker_id;  ?>" data-hireid="<?php echo $hireid; ?>" data-jobtitle="<?php echo $paymentData->cat_name; ?>"> Pay Now </a></td>
              </tr>
              <?php }
               else: 
                echo'<tr class="text-center"><td colspan="5">No Pending Payment</td></tr>';
            endif; ?>  

            </tbody>
          </table>




    </div>
        
@include('layouts.footer_admin') 
</div> 
</div>
<script type="text/javascript">
  jQuery(document).ready(function($){
    $('body').on('click', '.payNow', function(e){
      e.preventDefault();
      var payableamount  = $(this).data('payableamount');
      var clientid  = $(this).data('clientid');
      var worker_id  = $(this).data('workerid');
      var jobid  = $(this).data('jobid');
      var hireid  = $(this).data('hireid');
      var jobtitle  = $(this).data('jobtitle');
      if(confirm('Please confirm you want to process this payment.')){
      jQuery.ajax({ 
            method : 'GET',
            url  : "{{ url('/processclientpayments') }}",
            data:{'payableamount' : payableamount, 'clientid' : clientid, 'worker_id' : worker_id, 'jobid' : jobid , 'hireid' : hireid, 'jobtitle' : jobtitle }, 
            success :  function(resp) {
              //alert(resp)
              var data = jQuery.parseJSON( resp );
              alert( data.msg );
              
              console.log(data);
              window.location.reload();
              
              
            },
            error : function(resp){
              // var data = jQuery.parseJSON( resp );
               alert( 'Something went wrong.please try again.' );
               window.location.reload();
            }
      });
    }
    })
  })

</script>


@stop