routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('comingsoon');
});*/

Route::get('/', function () {
    return view('pages.home');
});

Route::get('/error', function () {
    return view('error');
});

/*Route::get('/chat', function () {
    return view('customerdashboard.chat');
});*/

Auth::routes();

Route::get('/chat', 'ChatController@index');
Route::post('ajaxRequest', 'ChatController@saveChat');
Route::get('getChat/{hireid}/{jobid}','ChatController@getChat');
Route::get('/chathistory/{jobid}','ChatController@getChathistory');
Route::get('/support', 'ChatController@show_adminchat');
Route::post('adminajaxRequest', 'ChatController@saveadminChat');
Route::get('getadminChat/{senderid}/{receiverid}','ChatController@getadminChat');
Route::get('getadminChatmsgcnt/{sndid}/{rcvid}','ChatController@getadminChatmsgcnt');

Route::get('/workeradminchat','ChatController@workeradminchat');
Route::post('workeradminajaxRequest', 'ChatController@saveworkeradminChat');
Route::get('getworkeradminChat/{senderid}/{receiverid}','ChatController@getworkeradminChat');

Route::get('/customeradminchat','ChatController@customeradminchat');
Route::post('customeradminajaxRequest', 'ChatController@savecustomeradminChat');
Route::get('getcustomeradminChat/{senderid}/{receiverid}','ChatController@getcustomeradminChat');

Route::get('/redirect/{service}', 'SocialAuthGoogleController@redirect');
Route::get('/callback/{service}', 'SocialAuthGoogleController@callback');

Route::get('/facebookredirect/{service}', 'SocialAuthFacebookController@facebookredirect');
Route::get('/facebookcallback/{service}', 'SocialAuthFacebookController@facebookcallback');


Route::get('/home', 'HomeController@index')->name('home');
Route::post('/home/store', 'HomeController@store');

Route::get('/pricing', 'PricingController@index')->name('pricing');
Route::get('/aboutus', 'AboutusController@index')->name('aboutus');

Route::get('auth/facebook', 'Auth/LoginController@redirectToProvider');
Route::get('auth/facebook/callback', 'Auth/LoginController@handleProviderCallback');
Route::get('userregister', 'Auth\LoginController@userregister');
Route::POST('/store','UsersController@store');
Route::GET('/storeclient','UsersController@storeclient');
Route::get('/checkuseremail', 'UsersController@checkuseremail');
Route::get('/checkloginemail', 'UsersController@checkloginemail');
/*Route::get('/checkloginpassword', 'UsersController@checkloginpassword');*/

Route::resource('jobpost','JobpostController');
Route::GET('/getequipment','JobpostController@getequipment');
Route::GET('/jobstore','JobpostController@jobstore');
Route::GET('/updatejob','JobpostController@updatejob');
Route::GET('/getalldata','JobpostController@getalldata');
Route::get('/reciept', 'JobpostController@reciept');
Route::get('/checkrefferalcode', 'JobpostController@checkrefferalcode');
Route::GET('/notitysec', 'JobpostController@notitysec');
Route::GET('/workernotitysec', 'JobpostController@workernotitysec');
Route::GET('/completeupdate', 'WorkerjobsController@complete_btn_status_update');
Route::GET('/cancelledupdate', 'WorkerjobsController@cancelled_btn_status_update');
Route::GET('/customercompleteupdate', 'CustomernotificationController@complete_btn_status_update');
Route::GET('/customercancelledupdate', 'CustomernotificationController@cancelled_btn_status_update');
Route::POST('/customerfeedback', 'CustomernotificationController@customer_feedback');
Route::POST('/workerfeedback', 'WorkerjobsController@worker_feedback');

Route::resource('workerdashboard','WorkerdashboardController');
Route::POST('/workerdashboard/store','WorkerdashboardController@store');
Route::get('/jobpreference','WorkerdashboardController@jobpreference');
Route::GET('/workerexperience','WorkerdashboardController@workerexperience');
Route::GET('/updtworkexp','WorkerdashboardController@updtworkexp');
Route::GET('/workerequipment','WorkerdashboardController@workerequipment');
Route::GET('/updtworkequ','WorkerdashboardController@updtworkequ');

Route::resource('customerdashboard','CustomerdashboardController');

Route::resource('customerpay', 'CustomerpaymentController');
Route::resource('customershare', 'CustomershareController');
Route::resource('customerjobs', 'CustomerjobsController');
Route::resource('customerjobhistory', 'CustomerjobhistoryController');
Route::resource('customergift', 'CustomergiftController');
Route::resource('customerhelp', 'CustomerhelpController');

Route::resource('workerpayment', 'WorkerpaymentController');
Route::resource('workerjobs', 'WorkerjobsController');
//================ 12-02-2019 ================//
Route::GET('/updateworkedhour', 'WorkerjobsController@updateWorkedHour'); 
Route::GET('/hourdetails', 'CustomernotificationController@hourDetails'); 
Route::GET('/updatehourstatus', 'CustomernotificationController@updateHourStatus'); 
Route::GET('/pendingpayments', 'AdminclientpaymentController@pendingPayments'); 
Route::GET('/adminallpayments', 'AdminclientpaymentController@adminAllPayments'); 
Route::GET('/createuserstripe', 'JobpostController@createUserStripe'); 
Route::GET('/processclientpayments', 'AdminclientpaymentController@processClientPayments'); 
Route::GET('/updatepoststatus', 'JobpostController@updatePostStatus'); 
Route::GET('/readallnotifications', 'JobpostController@readAllNotifications'); 
Route::GET('/updateworkerpayment', 'AdminrequestpaymentController@updateWorkerPayment'); 
//============================================//
Route::resource('workerprofile','WorkerdashboardController');
Route::resource('socialworkerprofile','WorkerdashboardController');
Route::resource('workershare','WorkershareController');
Route::resource('workerpay','WorkerpayController');
Route::resource('workerhelp','WorkerhelpController');
Route::GET('adminworker/update','AdminworkerController@update');
Route::GET('admincustomer/update','AdmincustomerController@update');

Route::GET('admindashboard','AdmindashboardController@index');

Route::POST('/adminupdate/worker','AdminupdateController@worker');
Route::POST('/adminupdate/customer','AdminupdateController@customer');
Route::resource('adminjobs','AdminjobsController');
Route::resource('adminhire','AdminhireController');
Route::POST('adminhirecreate','AdminhireController@adminhirecreate');
Route::GET('viewall','AdminhireController@viewall');
Route::resource('adminmessages','AdminmessagesController');
Route::POST('adminmessages/send_mail','AdminmessagesController@send_mail');
Route::resource('clientpayment','AdminclientpaymentController');
Route::resource('requestpayment','AdminrequestpaymentController');
Route::resource('adminprofile','AdminprofileController');
Route::resource('adminnotification','AdminnotificationController');
Route::resource('admincustomer','AdmincustomerController');
Route::resource('adminworker','AdminworkerController');
Route::resource('adminbussiness','AdminbussinessController');
Route::POST('/workerpay/store','WorkerpayController@store');
Route::POST('/update','WorkerpayController@update');
Route::POST('/update', 'WorkerjobsController@update');
Route::resource('customernotification', 'CustomernotificationController');
Route::POST('/update', 'CustomernotificationController@update');
Route::resource('workernotification', 'WorkernotificationController');
Route::POST('/update', 'WorkernotificationController@update');
Route::POST('/update', 'CustomerjobhistoryController@update');
Route::GET('/updatestatus', 'CustomerdashboardController@update_status');
Route::GET('/workersendinvitation', 'WorkershareController@worker_send_invitation_code');
Route::GET('/customersendinvitation', 'CustomershareController@customer_send_invitation_code');
Route::resource('customerpayment', 'CustomerpaymentsController');
Route::GET('/rejectpayment', 'AdminrequestpaymentController@reject_payment_update');

Route::GET('/forgetpassword', 'Auth\ForgotPasswordController@sendemail');
Route::GET('/checkforgetemail', 'Auth\ForgotPasswordController@checkforgotemail');

Route::POST('/workerprofileupdate/{id}','WorkerdashboardController@worker_profile_update');

resources/views/admin/jobs/edit.blade.php
@extends('layouts.defautladmin')

@section('title','Update User')

@section('content')
<div class="content Contextua_sec customers_detail">
    <h1>Edit Customer Profile</h1>
    @include('layouts.flash-message') 
<form method="POST" action="{{url('/')}}/adminupdate/customer" id="updateprofile" accept-charset="UTF-8" enctype='multipart/form-data'>
  {{ csrf_field() }}
  <div class="row bussiness">
<div class="col-sm-6"><label>First Name</label><input type="text" name="firstname" value="{{ $customer_info->firstname }}" required="required"></div>
<div class="col-sm-6"><label>Last Name</label><input type="text" name="lastname" value="{{ $customer_info->lastname }}" required="required"></div></div>
<div class="row bussiness">
<div class="col-sm-6"><label>Email Address</label><input type="text" name="email" value="{{ $customer_info->email }}" required="required"></div>
<div class="col-sm-6"><label>Phone</label><input type="text" name="phone" value="{{ $customer_info->phone }}" required="required"  onkeypress="this.value=this.value.replace(/[^0-9]/g,'');"></div>
</div>
<div class="row bussiness">
<div class="col-sm-6"><label>Password</label><input type="password" name="password" id="password"></div>    
<div class="col-sm-6"><label>Confirm Password</label><input type="password" name="confpwd" id="password"></div>
</div>
<div class="row bussiness">
  <div class="col-sm-6">
  <label>Profile Image</label>
  <input type="file" name="input_img">
<?php
if($customer_info->image==''){
  ?>
<img class="profileimage" src="{{ url('/public/admin/images/admin.jpg') }}">
<?php
}
else{
  ?>
<img class="profileimage" src="{{ url('/public/uploads/profile/')}}/{{ $customer_info->image }}">
<?php
}
?>
</div></div>
<div class="row bussiness">
<div class="col-sm-6"><label>City</label><input type="text" name="city" value="{{ $customer_info->city }}"></div>
<div class="col-sm-6"><label>State</label><input type="text" name="state" value="{{ $customer_info->state }}"></div></div>
<div class="row bussiness">
    <div class="col-sm-6"><label>Address</label><textarea name="address">{{ $customer_info->address }}</textarea>
</div>
	<div class="col-sm-6"><label>Address1</label><textarea name="address1">{{ $customer_info->address1 }}</textarea>
</div></div>
<div class="row bussiness"><div class="col-sm-6">
<input type="hidden" name="id" value="{{ $customer_info->id }}">
	<input type="submit" name="submit" value="Update" class="update_buss"></div></div>
</form>
<script type="text/javascript">
 $(document).ready( function() {
 $.validator.addMethod("alphaLetterNumber", function(value, element) {
     return this.optional(element) || value == value.match(/^[a-zA-Z0-9]+$/) && value.match(/[a-zA-Z0-9]/);
    });

  $.validator.addMethod("alphaLetterNumberSpace", function(value, element) {
     return this.optional(element) || value == value.match(/^[ a-zA-Z0-9]+$/) && value.match(/[a-zA-Z0-9]/);
    });

  $.validator.addMethod("alphaLetter", function(value, element) {
     return this.optional(element) || value == value.match(/^[ a-zA-Z]+$/) && value.match(/[a-zA-Z]/);
    });
     $.validator.addMethod("valueNotEquals", function(value, element, arg){
     return arg !== value;
  }, "Value must not equal arg.");
 $( "#updateprofile" ).validate({
  rules: {
                firstname: {
                    required: true,
                    alphaLetter:true,
                    minlength: 2,
                    maxlength: 150
                },
                lastname: {
                    required: true,
                    alphaLetter: true,
                    minlength: 2,
                    maxlength: 60
                },
                email: {
                    required: true,
                    email: true
                },
                phone: {
                  required: true,
                  minlength: 10,
                  maxlength: 14
                },
                address: {
                    required: true,
                    minlength: 6,
                    maxlength: 60
                },
                address1: {
                    required: true,
                    minlength: 6,
                    maxlength: 60
                },
                city: {
                    required: true
                },
                state: {
                    required: true
                }
  },
  messages: {
              firstname: {
                  required: "Please enter your firstname.",
                   alphaLetter:"Only letters are allowed",
                  minlength: "Minimum 2 characters required.",
                  maxlength: "Maximum 150 characters allowed."
                },
              lastname: {
                  required: "Please enter your lastname.",
                  alphaLetter:"Only letters are allowed",
                  minlength: "Minimum 2 characters required.",
                  maxlength: "Maximum 60 characters allowed."
                },
             
              email: {
                  required: "Please enter your email.",
                  email: "Enter valid email."                 
                },
                phone: {
                  required: "Please enter your phone number.",
                  minlength: "Minimum 10 digits required.",
                  maxlength: "Maximum 14 digits required."
                },
                address: {
                  required: "Please enter your Address.",
                  minlength: "Minimum 6 characters required.",
                  maxlength: "Maximum 60 characters allowed."
                },
                address1: {
                  required: "Please enter your Address.",
                  minlength: "Minimum 6 characters required.",
                  maxlength: "Maximum 60 characters allowed."
                },
                city: {
                    required: "Please enter your City."
                },
                state: {
                    required: "Please enter your State."
                }
              },
             
         });  

 });
</script>
</div>
 </div>
<style type="text/css">
.bussiness label { width: 32% }	
.bussiness { margin: 10px 0 10px 0; }
textarea {
    border: 1px solid #25a6dc;
    border-radius: 5px;
    padding: 0px 10px;
    background-color: #e5f1f6;
}
#password {
    border: 1px solid #25a6dc;
    border-radius: 5px;
    padding: 0px 10px;
    background-color: #e5f1f6;
    height: 38px;
}
.update_buss {
    border: 1px solid #25a6dc;
    border-radius: 5px;
    padding: 0px 10px;
    background-color: #e5f1f6;	
    cursor: pointer;
    height: 36px;
}
</style> 
 @stop

resources/views/admin/jobs/index.blade.php
@extends('layouts.defautladmin')

@section('title', 'Job Listing')

@section('content')

<div class="content customers_detail">
	<div class="col-sm-12">
	    <div class="adminjob">
		    <h2>Job Listing <span class="badge pull-right"> 
			    <form action="" method="get" class="getform">
			        <p></p>
			        <!--<input type="text" placeholder="Search.." name="search">-->
                 <!--<button type="submit"><i class="fa fa-search"></i></button>-->
                </form>
            </h2>
        </div>
	</div>
	<div class="col-sm-12">
		  <table class="table-width col_or">
		    <thead>
		      <tr class="table-active">
		        <th class="col3">Heading</th>
		      	<th class="col4">Description</th>
		      	<th class="col4">Requested Worker</th>
		      	<th class="col3">Hours</th>

<!--		        <th>Package</th>
-->		        <th class="col4">Created At</th>
                <th class="col2">View</th>
		      </tr>
		    </thead>
		    <?php $count=count($jobs_info); ?>
          	@if($count > '0')
		    @foreach($jobs_info as $jobs)
		      <tr>
		        <td class="col3">{{ $jobs->cat_name }}</td>
		        <td class="col5">{{ $jobs->job_description }}</td>
		        <td class="col3">{{ $jobs->worker_required }}</td>
		        <td class="col3">{{ $jobs->start_time }}</td>
		        <td class="col4">{{ $jobs->created_at }}</td>
		       <td class="col1"><a href="{{route('adminjobs.show', $jobs->id)}}"><i class="fa fa-eye" style="font-size:15px"></i></a></td>
		      </tr>      
@endforeach
@else
<tr>
	<td></td>
	<td></td>
	<td>No Jobs Here...</td>
	<td></td>
</tr>
@endif

		    </tbody>
		  </table>
	</div>
<div class="content pagi_div">
    {{ $jobs_info->appends(Request::only('s', 'show'))->links() }} 
</div>
@include('layouts.footer_admin') 
  
</div> 

    </div>
    @stop

resources/views/admin/jobs/show.blade.php
@extends('layouts.defautladmin')

@section('title', 'Job Listing')

@section('content')

<!--<div class="content Contextua_sec customers_detail">
	<div class="col-sm-12">
		<h2>Job Listing <span class="badge pull-right"> 
			<!--<form action="" method="get"><input type="text" placeholder="Search.." name="search">-->
   <!--                           <button type="submit"><i class="fa fa-search"></i></button></form>-->
                             <!-- </h2>
        
	</div>
	<div class="col-sm-12">
		  <table class="table-width col_or">
		    <thead>
		      <tr class="table-active">
		        <th>Heading</th>
		      	<th>Description</th>
		        <th>Package</th>
		        <th>Created At</th>
		      </tr>
		    </thead>
		    @foreach($jobs_info as $jobs)
		      <tr>
		        <td>{{ $jobs->cat_name }}</td>
		        <td>{{ $jobs->job_description }}</td>
                <td>{{ ucfirst($jobs->worker_type) }}</td>
		        <td>{{ $jobs->created_at }}</td>
		        
<!--		      </tr>      -->
<!--@endforeach-->
		  <!--  </tbody>
		  </table>
	</div>
<div class="content pagi_div">
    {{ $jobs_info->appends(Request::only('s', 'show'))->links() }} 
</div>
@include('layouts.footer_admin') 
  
</div> 

    </div>-->
    <!--modified 1dec2018-->
    @foreach($jobs_info as $jobs)
<!--{{ $jobs->cat_name }} 
 {{ $jobs->job_description }}
{{ ucfirst($jobs->worker_type) }}
{{ $jobs->created_at }}-->
@endforeach

<div class="tab-pane active text-style" id="tab1">
        <div class="content customers_detail">
       <div class="col-md-12 rightcontent">
        
  <div class="">
    <div role="tabpanel" class="" id="openjobs">
      <div class="">
      	 <div class="">
      	    <div class="adminjob">
                <h2>Details</h2>
            </div>
           
            <?php 
            //echo'<pre>';
            //print_r($hireData);
            //echo'</pre>';

            ?>

          <table class="table-view">
          <tr class="headings"><th class="column1">Category</th><td>{{ $jobs->cat_name}}</td> </tr>  
          <tr class="headings"><th class="column1">Description</th><td>{{ $jobs->job_description }}</td> </tr>
          <tr class="headings"><th class="column1">Workertype</th><td> {{ ucfirst($jobs->worker_type) }}</td></tr>
          <tr class="headings"><th class="column1">Hours</th><td> {{ $jobs->start_time }}
          </td></tr>
          <tr class="headings"><th class="column1">Created at</th><td> {{ $jobs->created_at }}</td></tr>

           <tr class="headings"><th class="column1"><a href="{{url('/chathistory').'/'.$id}}" class="historybtn">Chat history</a></th></tr>
           
          </table></div></div>
          <?php if(!empty($hireData)):?>
            <div class="adminjob">
                <h2 class="text-center">Worker Details</h2>
              </div>
            <div class="table-responsive">
               
               
               <table class="table table-striped">
                  <tr>
                    <th>Worker ID</th>
                    <th>Worker Name</th>
                    <th>Job Status</th>
                    <th>Work Timesheet</th>
                    <th>Job Summary(Worker)</th>
                    <th>Future Appointments</th>
                    <th>Private Notes</th>
                    <th>Updated Timesheet</th>
                    
                  </tr>
                  <?php foreach( $hireData as $_hiredata  ): ?>
                    <tr>
                    <td><?php echo $_hiredata->worker_id; ?></td>
                    <td><?php echo $_hiredata->name; ?></td>
                    <td><?php echo $_hiredata->job_status; ?></td>
                    <td><?php if($_hiredata->hours_to_complete !=''): echo '<label class="badge badge-success">'. $_hiredata->hours_to_complete .':'. $_hiredata->mints_to_complete .'hr</label>'; endif; ?></td>
                    <td><small><?php echo $_hiredata->job_summary; ?></small></td>
                    <td><small><?php echo $_hiredata->future_appointments; ?></small></td>
                    <td><small><?php echo $_hiredata->private_notes; ?></small></td>
                    <td><?php if($_hiredata->updated_hours !=''): echo '<label class="badge badge-success">'. $_hiredata->updated_hours .':'. $_hiredata->updated_mints .'hr</label>'; endif; ?></td>
                    </tr>
                  <?php endforeach; ?>

               </table> 
               </div>  
          <?php endif;?>
        </div></div>
          
          <style>
table.table-view td {
    padding: 15px;
    font-size: 16px;
    color: #666666;
}
table.table-view td.column1 {
    width: 200px;
}
table.table-view a.view-table {
    display: block;
    width: 120px;
    border: 1px solid #cdcfd9;
    text-align: center;
    padding: 10px;
    border-radius: 5px;
    color: #1aa3df;
    font-size: 17px;
    background: #f3f5f8;
    text-decoration: none;
}
table.table-view tr.headings th {
    font-size: 15px;
    color: #333333;
    padding: 20px 15px;
}
table.table-view thead {
    background: #f6f6f6;
}
table.table-view td.column1 {
    font-size: 17px;
    color: #666666;
    font-family: "ProximaNova-Semibold";
}
table.table-view {
    border: 1px solid #e4e4e4;
    background-color: #f6f6f6;
    width: 100%;
}
.dashboard-right {
    background: #e5f1f6;
    padding: 25px 30px;
}
.tab-content {
    padding-left: 20px;
    padding-top: 44px;
}
.historybtn {
    background-color: #25a6dc;
    border: 1px solid #25a6dc;
    color: #fff;
    font-size: 14px;
    font-weight: 600;
    padding: 10px;
    border-radius: 5px;
    float: left;
    /*margin: 15px;*/
}
.historybtn:hover, .historybtn:active, .historybtn:focus  {color:#fff;text-decoration:none;}
</style>

    @stop